# ── Worker, its storage, and the hostname it answers on ──────────────────────

resource "cloudflare_workers_kv_namespace" "events" {
  account_id = local.account_id
  title      = "edge-guard-events"
}

# The posture the page renders. Built from the very same locals the ruleset
# resources consume, so the table on the page cannot drift from what is applied.
locals {
  posture = {
    zone      = var.zone_name
    hostname  = var.hostname
    plan      = "Free"
    generated = "terraform"
    ai_model  = local.ai_model
    turnstile = { mode = "managed", sitekey = cloudflare_turnstile_widget.edge_guard.sitekey }
    ddos_note = "L3-L7 DDoS managed rulesets are always on and unmetered on every plan. Overrides need Enterprise + Advanced DDoS, so none are declared."
    bot_fight_mode = {
      enabled     = var.enable_bot_fight_mode
      scope       = "zone-wide"
      description = "Bot Fight Mode cannot be scoped to one hostname on Free, so it also covers the main site. It requires JavaScript Detections, which is enabled with it and is also zone-wide."
    }
    zone_settings = [
      { setting = "always_use_https", value = "on", scope = "zone-wide" },
      { setting = "min_tls_version", value = "1.2", scope = "zone-wide" },
      { setting = "security_header (HSTS)", value = "max-age=31536000", scope = "zone-wide" },
    ]
    rules = concat(
      [for r in local.waf_rules : {
        phase       = "http_request_firewall_custom"
        scope       = r.scope
        expression  = r.expression
        action      = r.action
        description = r.description
      }],
      [{
        phase       = "http_ratelimit"
        scope       = local.ratelimit.scope
        expression  = local.ratelimit.expression
        action      = "${local.ratelimit.action} (${local.ratelimit.requests_per_period} req / ${local.ratelimit.period}s per IP, ${local.ratelimit.mitigation_timeout}s timeout)"
        description = local.ratelimit.description
      }],
      [{
        phase       = "http_request_cache_settings"
        scope       = local.cache_rule.scope
        expression  = local.cache_rule.expression
        action      = "${local.cache_rule.action} (edge TTL ${local.cache_rule.edge_ttl}s)"
        description = local.cache_rule.description
      }],
    )
  }

  ai_model = "@cf/meta/llama-3.3-70b-instruct-fp8-fast"
}

resource "cloudflare_workers_script" "edge_guard" {
  account_id         = local.account_id
  script_name        = "edge-guard"
  main_module        = "index.js"
  content_file       = "${path.module}/../worker/dist/index.js"
  content_sha256     = filesha256("${path.module}/../worker/dist/index.js")
  compatibility_date = "2026-09-01"

  bindings = [
    {
      name = "AI"
      type = "ai"
    },
    {
      name         = "EVENTS"
      type         = "kv_namespace"
      namespace_id = cloudflare_workers_kv_namespace.events.id
    },
    {
      name = "POSTURE"
      type = "plain_text"
      text = jsonencode(local.posture)
    },
    {
      name = "TURNSTILE_SECRET"
      type = "secret_text"
      text = cloudflare_turnstile_widget.edge_guard.secret
    },
    {
      name = "AI_MODEL"
      type = "plain_text"
      text = local.ai_model
    },
  ]

  observability = {
    enabled = true
  }

  # Workers Cache. Zone cache rules do NOT govern a Worker's own generated
  # response (Cloudflare docs: "No zone configuration for caching applies to
  # Workers Caching"), so the /static/* MISS-then-HIT demo needs this switch.
  # The cache rule in cache.tf is still real and still applied: it is simply the
  # wrong layer for Worker-generated bytes. Both are declared here in Terraform.
  cache_options = {
    enabled = true
  }
}

# Creates its own proxied DNS record for edge-guard.diogodebastos.com only.
# The apex and www stay with wrangler and are never referenced here.
resource "cloudflare_workers_custom_domain" "edge_guard" {
  account_id = local.account_id
  zone_id    = local.zone_id
  hostname   = var.hostname
  service    = cloudflare_workers_script.edge_guard.script_name
}
